theme: vuepress

siteConfig:
  title: Community Events
  description: Directory for event ideas and proposals for developer communities, placing DSC KGEC in focus. 
  author: Ayush Singh
  email: coding.ayush@gmail.com

themeConfig:
  nav:
    - text: Event Ideas
      link: /
    - text: Project Ideas
      link: /projects.html
  repo:
      - site: Github
        name: singhayushh
  
plugins:
  - resolve: saber-plugin-query-posts

markdown:
  plugins:
    - resolve: markdown-it-div
